User.destroy_all
Recipe.destroy_all
Ingredient.destroy_all
IngredientRecipe.destroy_all
Allergy.destroy_all

u1 = User.create(name: "Harriet")
u2 = User.create(name: "Richie")
u3 = User.create(name: "Danny")
u4 = User.create(name: "Dunia")
u5 = User.create(name: "Patrick")

r1 = Recipe.create(user_id: u1.id, title: "Scrambled Tofu on toast")
r2 = Recipe.create(user_id: u2.id, title: "Chilli Con Carne")
r3 = Recipe.create(user_id: u3.id,title: "Massamun Beef Curry")
r4 = Recipe.create(user_id: u4.id,title: "Mushroom Risotto")
r5 = Recipe.create(user_id: u5.id,title: "Lentil Dahl")
r6 = Recipe.create(user_id: u1.id,title: "Fish Pie")
r7 = Recipe.create(user_id: u2.id,title: "Miso Baked Cod")
r8 = Recipe.create(user_id: u3.id,title: "Green Bean Yakisoba")
r9 = Recipe.create(user_id: u4.id,title: "Baked Alaska")
r10 = Recipe.create(user_id: u5.id,title: "Mille Feuille")

tofu = Ingredient.create(name: "tofu")
rice = Ingredient.create(name: "rice")
cod = Ingredient.create(name: "cod")
lentils = Ingredient.create(name: "lentils")
mushrooms = Ingredient.create(name: "mushroom")
pastry = Ingredient.create(name: "pastry")
potatoes = Ingredient.create(name: "potato")
beans = Ingredient.create(name: "green beans")
noodles = Ingredient.create(name: "noodles")
sugar = Ingredient.create(name: "sugar")
egg = Ingredient.create(name: "egg")
beef = Ingredient.create(name: "beef")
chilli = Ingredient.create(name: "chilli")
tomatoes = Ingredient.create(name: "tomato")
soy = Ingredient.create(name: "soy sauce")
coconut = Ingredient.create(name: "coconut milk")
turmeric = Ingredient.create(name: "turmeric")
spring_onion = Ingredient.create(name: "spring onion")
bread = Ingredient.create(name: "bread")
curry = Ingredient.create(name: "curry paste")
cheese = Ingredient.create(name: "cheese")
strawberry = Ingredient.create(name: "strawberry")
ice_cream = Ingredient.create(name: "ice cream")

ri1 = IngredientRecipe.create(recipe_id: r1.id, ingredient_id: bread.id)
ri2 = IngredientRecipe.create(recipe_id: r9.id, ingredient_id: egg.id)
ri3 = IngredientRecipe.create(recipe_id: r5.id, ingredient_id: tomatoes.id)
ri4 = IngredientRecipe.create(recipe_id: r6.id, ingredient_id: cheese.id)
ri5 = IngredientRecipe.create(recipe_id: r4.id, ingredient_id: mushrooms.id)
ri6 = IngredientRecipe.create(recipe_id: r4.id, ingredient_id: rice.id)
ri7 = IngredientRecipe.create(recipe_id: r4.id, ingredient_id: cheese.id)
ri8 = IngredientRecipe.create(recipe_id: r9.id, ingredient_id: ice_cream.id)

a1 = Allergy.create(ingredient_id: ice_cream.id, user_id: u3.id)
a2 = Allergy.create(ingredient_id: cheese.id, user_id: u1.id)
a3 = Allergy.create(ingredient_id: tomatoes.id, user_id: u5.id)
a4 = Allergy.create(ingredient_id: pastry.id, user_id: u1.id)
a5 = Allergy.create(ingredient_id: soy.id, user_id: u4.id)
